function big() { sudo find . -type f -size +"$1"M -exec ls -lh {} \; | awk '{ print $9 ": " $5 }'; }
function password() { openssl rand -base64 32; }
function search() { grep -rn . -e "$1";}
function stash() { cd /Users/michael.perzel/stash; }

function dd() {docker "$1" $(docker ps -aq); } # docker do

alias ap="ansible-playbook"

